### ISSUE TITLE
Errors when starting up

### ISSUE THREAD

**Issue by davidmashburn** [jaclarke/edgedb-ui#8]
I tried following the README and ran into some issues. Everything seemed ok until I hit the npm start and I got the error message that follows below. I tried wiping the repo clean and running again 3 or 4 times and Google does not seem to have any easy answers here. I'm not sure if the problem is a missing connections.json file, node fuse, pacakge incompatibilities, or something else.

I'm no node expert, so maybe there is just something obvious I should do differently?

.......

└── zod@1.2.3 56.7 kB (0 files)
size: 1.6 MB in 2s 117ms

  -------------- 

Errors for renderer bundle
  → ERROR Asset reference "renderer/components/schemaView/schemaDetails.vue" has failed to resolve in module "default"

  -------------- 

--------------------------
Bundle "schemaLayoutWorker" 

    workers/schemaLayout/aStar.js
    workers/schemaLayout/layout.js
    workers/schemaLayout/routeLinks.js
└──  (3 files,  26.2 kB) default
└── fastpriorityqueue@0.6.3 9 kB (0 files)
└── tslib@1.10.0 11.9 kB (0 files)
└── webcola@3.4.0 406.9 kB (0 files)
size: 454.1 kB in 218ms
16:15:30: Launching socket server on 4444
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
[Error: ENOENT: no such file or directory, open '~/.config/Electron/connections.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '~/.config/Electron/connections.json'
}
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: ENOSPC: System limit for number of file watchers reached, watch '~/edgedb-ui/src/edgedb/node_modules/json-schema-traverse/README.md'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1329:11)
    at createFsWatchInstance (~/edgedb-ui/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (~/edgedb-ui/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (~/edgedb-ui/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile ~/edgedb-ui/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (~/edgedb-ui/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqCallback.oncomplete (fs.js:159:5)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (~/edgedb-ui/node_modules/chokidar/index.js:257:10)
    at createFsWatchInstance (~/edgedb-ui/node_modules/chokidar/lib/nodefs-handler.js:39:5)
    at setFsWatchListener (~/edgedb-ui/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    [... lines matching original stack trace ...]
    at FSReqCallback.oncomplete (fs.js:159:5) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '~/edgedb-ui/src/edgedb/node_modules/json-schema-traverse/README.md',
  filename: '~/edgedb-ui/src/edgedb/node_modules/json-schema-traverse/README.md'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! edgedb-ui@0.0.1 start: `node fuse`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the edgedb-ui@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2021-08-27T20_15_30_995Z-debug.log

---------------------------
~/.npm/_logs/2021-08-27T20_15_30_995Z-debug.log:
---------------------------

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '~/.nvm/versions/node/v12.13.1/bin/node',
1 verbose cli   '~/.nvm/versions/node/v12.13.1/bin/npm',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.12.1
3 info using node@v12.13.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle edgedb-ui@0.0.1~prestart: edgedb-ui@0.0.1
6 info lifecycle edgedb-ui@0.0.1~start: edgedb-ui@0.0.1
7 verbose lifecycle edgedb-ui@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle edgedb-ui@0.0.1~start: PATH: ~/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:~/edgedb-ui/node_modules/.bin:~/.nvm/versions/node/v12.13.1/bin:~/.local/bin:~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle edgedb-ui@0.0.1~start: CWD: ~/edgedb-ui
10 silly lifecycle edgedb-ui@0.0.1~start: Args: [ '-c', 'node fuse' ]
11 silly lifecycle edgedb-ui@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle edgedb-ui@0.0.1~start: Failed to exec start script
13 verbose stack Error: edgedb-ui@0.0.1 start: `node fuse`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (~/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (~/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid edgedb-ui@0.0.1
15 verbose cwd ~/edgedb-ui
16 verbose Linux 5.4.0-80-generic
17 verbose argv "~/.nvm/versions/node/v12.13.1/bin/node" "~/.nvm/versions/node/v12.13.1/bin/npm" "start"
18 verbose node v12.13.1
19 verbose npm  v6.12.1
20 error code ELIFECYCLE
21 error errno 1
22 error edgedb-ui@0.0.1 start: `node fuse`
22 error Exit status 1
23 error Failed at the edgedb-ui@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by davidmashburn** [comment]
One of the issues (ENOSPC: System limit for number of file watchers reached) was a Linux issue, found a work-around here: https://stackoverflow.com/questions/55763428/react-native-error-enospc-system-limit-for-number-of-file-watchers-reached)

The error:

Errors for renderer bundle
  → ERROR Asset reference "renderer/components/schemaView/schemaDetails.vue" has failed to resolve in module "default"

is still causing problems for me.
